apiVersion: v1
kind: ConfigMap
metadata:
  name: popular-config
data:
  {{ .Values.configNames.port }}: {{ .Values.appPort | quote }}
  {{ .Values.configNames.postgresHost }}: {{ include "postgresql.fullname" . }}
  {{ .Values.configNames.postgresPort }}: {{ .Values.postgresql.service.port | quote }}
  {{ .Values.configNames.postgresDbName }}: {{ .Values.postgresql.postgresqlDatabase }}
  {{ .Values.configNames.postgresUser }}: {{ .Values.postgresql.postgresqlUsername }}
  {{ .Values.configNames.redisHost }}: {{ include "redis.fullname" . }}-headless
  {{ .Values.configNames.redisPort }}: {{ .Values.redis.redisPort | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: popular-secret
type: Opaque
data:
  {{ .Values.configNames.postgresPassword }}: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{ .Values.configNames.redisPassword }}: {{ .Values.redis.password | b64enc | quote }}