apiVersion: v1
kind: Service
metadata:
  name: {{ include "popular-chart.fullname" . }}
  labels:
    {{- include "popular-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.appPort }}
      name: http
  selector:
    {{- include "popular-chart.selectorLabels" . | nindent 4 }}
