replicaCount: 2

image:
  repository: ilyashikhaleev/arch-course

service:
  type: NodePort
  port: 9000

appPort: 8000

ingress:
  host: "arch.homework"
  enabled: true
  paths: ["/otusapp($|/)(.*)"]
  hosts: ["arch.homework"]
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

postgresql:
  postgresqlDatabase: archapp-db
  postgresqlUsername: archappuser
  postgresqlPassword: passwd
  service:
    port: "5432"