apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arch-chart.fullname" . }}
  labels:
    {{- include "arch-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "arch-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arch-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.appPort }}
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: archapp-config
                  key: PORT
            - name: POSTGRES_HOST
              value: {{ include "postgresql.fullname" . }}
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: archapp-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: archapp-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: archapp-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: archapp-secret
                  key: POSTGRES_PASSWORD

          livenessProbe:
            httpGet:
              port: {{ .Values.appPort }}
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: {{ .Values.appPort }}
              path: /ready
            initialDelaySeconds: 10
            periodSeconds: 5