apiVersion: apps/v1
kind: Deployment
metadata:
  name: arch-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: arch-app
  template:
    metadata:
      labels:
        app: arch-app
    spec:
      containers:
        - name: arch-app
          image: ilyashikhaleev/arch-course:0.0.6
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: archapp-config
                  key: PORT
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: archapp-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: archapp-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: archapp-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: archapp-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: archapp-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: web
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /ready
            initialDelaySeconds: 10
            periodSeconds: 5

