apiVersion: apps/v1
kind: Deployment
metadata:
  name: arch-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: arch-app
  template:
    metadata:
      labels:
        app: arch-app
    spec:
      containers:
        - name: arch-app
          image: ilyashikhaleev/arch-course:0.0.6
          env:
            - name: PORT
              value: "8000"
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: archapp-db
            - name: POSTGRES_USER
              value: archappuser
            - name: POSTGRES_PASSWORD
              value: passwd
          ports:
            - name: web
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /ready
            initialDelaySeconds: 10
            periodSeconds: 5

