apiVersion: batch/v1
kind: Job
metadata:
  name: "post-install-job"
spec:
  template:
    metadata:
      name: "post-install-job"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "passwd"
          command:
            - sh
            - "-c"
            - |
              psql postgres://archappuser:passwd@postgres/archapp-db <<'EOF'
                CREATE TABLE users (
                id          varchar(36),
                username    varchar(255),
                firstname   text,
                lastname    text,
                email       text,
                phone       text,
                CONSTRAINT id_key PRIMARY KEY(id),
                CONSTRAINT uniq_username UNIQUE(username)
                );
              EOF

  backoffLimit: 0