apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-info-chart.fullname" . }}
  labels:
    {{- include "user-info-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-info-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-info-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.appPort }}
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: user-info-config
                  key: {{ .Values.configNames.port }}

          livenessProbe:
            httpGet:
              port: {{ .Values.appPort }}
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: {{ .Values.appPort }}
              path: /ready
            initialDelaySeconds: 10
            periodSeconds: 5