apiVersion: batch/v1
kind: Job
metadata:
  name: "stresstest-job"
  labels:
    {{- include "arch-chart.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        {{- include "arch-chart.selectorLabels" . | nindent 8 }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
    spec:
      hostAliases:
        - ip: "192.168.20.186"
          hostnames:
            - "arch.homework"
      restartPolicy: Never
      containers:
        - name: stresstest-job
          image: jordi/ab@sha256:e73ba5f38be047448267bcfbab191bbea88017150578ef2dd3b0942a0e0d6a56
          command:
            - sh
            - "-c"
            - |
              while true; do ab -n50 -c5 http://arch.homework/otusapp/api/v1/users/{{ .Values.test.user }} ; sleep 3; done

  backoffLimit: 0