replicaCount: 1

image:
  repository: ilyashikhaleev/arch-course-auth

service:
  type: NodePort
  port: 9000

test:
  user: 2c801978-815c-11ea-a3d4-02420a200002

appPort: 8000
configNames:
  port: PORT

ingress:
  enabled: false
