apiVersion: v2
name: popular-chart
description: A Helm chart for Kubernetes

type: application

version: 0.0.1

appVersion: 0.0.1

dependencies:
  - name: traefik
    version: "1.86.*"
    repository: "https://kubernetes-charts.storage.googleapis.com"
    condition: ingress.enabled