apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payment-chart.fullname" . }}
  labels:
    {{- include "payment-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "payment-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "payment-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.appPort }}
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: {{ .Values.configNames.port }}
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: {{ .Values.configNames.postgresHost }}
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: {{ .Values.configNames.postgresPort }}
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: {{ .Values.configNames.postgresDbName }}
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: {{ .Values.configNames.postgresUser }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: {{ .Values.configNames.postgresPassword }}

          livenessProbe:
            httpGet:
              port: {{ .Values.appPort }}
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: {{ .Values.appPort }}
              path: /ready
            initialDelaySeconds: 10
            periodSeconds: 5