apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "payment-chart.fullname" . }}
  labels:
    {{- include "payment-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "payment-chart.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "payment-chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 5s
      port: http
      path: /metrics