{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "user-chart.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $guestPaths := .Values.ingress.guest.paths -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "user-chart.fullname" . }}-guest
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}
  {{- if .Values.ingress.guest.annotations }}
  annotations:
  {{ toYaml .Values.ingress.guest.annotations | nindent 4 }}
{{- end }}
spec:
  rules:
  {{- if .Values.ingress.hosts }}
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
  {{- range $p := $guestPaths }}
      - path: {{ $p }}
        backend:
          serviceName: {{ $serviceName }}
          servicePort: {{ $servicePort }}
  {{- end -}}
  {{- end -}}
  {{- end -}}
{{- end -}}