apiVersion: batch/v1
kind: Job
metadata:
  name: "post-install-job"
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        {{- include "user-chart.selectorLabels" . | nindent 8 }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: postgres:latest
          env:
            - name: DATABASE_URI
              value: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | quote }}
          command:
            - sh
            - "-c"
            - |
              psql $DATABASE_URI <<'EOF'
                CREATE TABLE users (
                  id          varchar(36),
                  username    varchar(255),
                  password    varchar(255),
                  firstname   text,
                  lastname    text,
                  email       text,
                  phone       text,
                  CONSTRAINT id_key PRIMARY KEY(id),
                  CONSTRAINT uniq_username UNIQUE(username)
                );
                INSERT INTO users (id, username, password, firstname, lastname, email, phone)
                VALUES ('{{ .Values.test.user }}', 'johndoe567', '098f6bcd4621d373cade4e832627b4f6', 'John', 'Doe', 'bestjohn@doe.com', '+71002003040')
                ON CONFLICT (id) DO UPDATE SET username = EXCLUDED.username,
                                             firstname  = EXCLUDED.firstname,
                                             lastname   = EXCLUDED.lastname,
                                             email      = EXCLUDED.email,
                                             phone      = EXCLUDED.phone;
                CREATE TABLE meta_products (
                  id          varchar(36),
                  title       varchar(255),
                  description varchar(255),
                  material    integer,
                  CONSTRAINT meta_products_key PRIMARY KEY(id)
                );
                INSERT INTO meta_products (id, title, description, material)
                VALUES (
                          '2c801978-815c-11ea-a3d4-02420a200002',
                          'Gopher',
                          'This beautiful paper polygonal gopher will decorate your Go event, your office or your apartment. If you are a fan of the Go language, then you definitely need to have such a gopher.',
                          1
                        ), (
                          'c752e5dd-da79-11ea-ab94-02420a200004',
                          'Gopher',
                          'This fullmetal polygonal gopher will decorate your Go event, your office or your apartment. If you are a fan of the Go language, then you definitely need to have such a gopher.',
                          2
                        ), (
                          'db75861e-da7e-11ea-ab94-02420a200004',
                          'Gopher',
                          'This template of polygonal gopher will decorate your Go event, your office or your apartment. If you are a fan of the Go language, then you definitely need to have such a gopher.',
                          3
                        )
                ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title,
                                               description = EXCLUDED.description,
                                               material = EXCLUDED.material;
                CREATE TABLE products (
                  id              varchar(36),
                  meta_product_id varchar(36),
                  height          integer DEFAULT NULL,
                  color           varchar(255) DEFAULT NULL,
                  price           float,
                  CONSTRAINT products_key PRIMARY KEY(id)
                );
                INSERT INTO products (id, meta_product_id, height, color, price)
                VALUES (
                          '72eb9cf0-da7f-11ea-ab94-02420a200004',
                          '2c801978-815c-11ea-a3d4-02420a200002',
                          35,
                          'blue',
                          10.0
                        ), (
                          '47a0810a-da7f-11ea-ab94-02420a200004',
                          '2c801978-815c-11ea-a3d4-02420a200002',
                          65,
                          'blue',
                          20.0
                        ), (
                          '4dd15bb6-da7f-11ea-ab94-02420a200004',
                          '2c801978-815c-11ea-a3d4-02420a200002',
                          35,
                          'brown',
                          9.99
                        ),(
                          'dcbf686f-da7f-11ea-ab94-02420a200004',
                          '2c801978-815c-11ea-a3d4-02420a200002',
                          65,
                          'brown',
                          20.0
                        ), (
                          '5711d9b6-da7f-11ea-ab94-02420a200004',
                          'c752e5dd-da79-11ea-ab94-02420a200004',
                          40,
                          'metal',
                          30.0
                        ), (
                          '6b1c1c3f-da7f-11ea-ab94-02420a200004',
                          'c752e5dd-da79-11ea-ab94-02420a200004',
                          60,
                          'blue',
                          40.0
                        ), (
                          '84104e38-da7f-11ea-ab94-02420a200004',
                          'c752e5dd-da79-11ea-ab94-02420a200004',
                          100,
                          'blue',
                          55.5
                        ), (
                          '7bc0687e-da7f-11ea-ab94-02420a200004',
                          'db75861e-da7e-11ea-ab94-02420a200004',
                          NULL,
                          NULL,
                          5.0
                        )
                ON CONFLICT (id) DO UPDATE SET meta_product_id = EXCLUDED.meta_product_id,
                                               height = EXCLUDED.height,
                                               color = EXCLUDED.color,
                                               price = EXCLUDED.price;
                CREATE TABLE carts (
                  id              varchar(36),
                  user_id         varchar(36),
                  CONSTRAINT carts_key PRIMARY KEY(id)
                );
                CREATE TABLE carts_products (
                  cart_id            varchar(36),
                  product_id         varchar(36)
                );
                CREATE TABLE orders (
                  id              varchar(36),
                  user_id         varchar(36),
                  status          integer,
                  CONSTRAINT orders_key PRIMARY KEY(id)
                );
                CREATE TABLE orders_products (
                  order_id   varchar(36),
                  product_id varchar(36),
                  price      float
                );
                CREATE TABLE popular (
                  product_id  varchar(36),
                  title       varchar(255),
                  description varchar(255),
                  material    varchar(255),
                  height      integer DEFAULT NULL,
                  color       varchar(255) DEFAULT NULL,
                  price       float,
                  buy_count   integer,
                  CONSTRAINT  popular_key PRIMARY KEY(product_id)
                );
              EOF

  backoffLimit: 5