apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-chart.fullname" . }}
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.appPort }}
      name: http
  selector:
    {{- include "user-chart.selectorLabels" . | nindent 4 }}
