replicaCount: 2

image:
  repository: ilyashikhaleev/arch-course

service:
  type: NodePort
  port: 9000

test:
  user: 2c801978-815c-11ea-a3d4-02420a200002

appPort: 8000

ingress:
  host: "arch.homework"
  enabled: true
  paths: ["/otusapp($|/)(.*)"]
  hosts: ["arch.homework"]
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

postgresql:
  postgresqlDatabase: archapp-db
  postgresqlUsername: archappuser
  postgresqlPassword: passwd
  service:
    port: "5432"

metrics:
  serviceMonitor:
    enabled: true

configNames:
  port: PORT
  postgresHost: POSTGRES_HOST
  postgresPort: POSTGRES_PORT
  postgresDbName: POSTGRES_DB
  postgresUser: POSTGRES_USER
  postgresPassword: POSTGRES_PASSWORD
