replicaCount: 2

image:
  repository: ilyashikhaleev/arch-course

service:
  type: NodePort
  port: 9000

test:
  user: 2c801978-815c-11ea-a3d4-02420a200002

appPort: 8000

ingress:
  host: "arch.homework"
  enabled: true
  paths: ["/otusapp"]
  hosts: ["arch.homework"]
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: http,https
    traefik.frontend.rule.type: PathPrefixStrip

postgresql:
  postgresqlDatabase: archapp-db
  postgresqlUsername: archappuser
  postgresqlPassword: passwd
  service:
    port: "5432"

metrics:
  serviceMonitor:
    enabled: true

configNames:
  port: PORT
  postgresHost: POSTGRES_HOST
  postgresPort: POSTGRES_PORT
  postgresDbName: POSTGRES_DB
  postgresUser: POSTGRES_USER
  postgresPassword: POSTGRES_PASSWORD

prometheus-postgres-exporter:
  serviceMonitor:
    enabled: true
    interval: 15s
  config:
    autoDiscoverDatabases: true
    datasourceSecret:
      name: archapp-secret
      key: posgressUri

traefik:
  rbac:
    enabled: true
  accessLogs:
    enabled: true
  metrics:
    prometheus:
      enabled: true
    serviceMonitor:
      enabled: true
  ssl:
    enabled: false
  deployment:
    hostPort:
      httpEnabled: true
      httpsEnabled: false
  serviceType: NodePort

prometheus-operator:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelector: {}
  grafana:
    sidecar:
      dashboards:
        enabled: true
        label: grafana-dashboard
