apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  {{ .Values.configNames.port }}: {{ .Values.appPort | quote }}
  {{ .Values.configNames.postgresHost }}: {{ include "postgresql.fullname" . }}
  {{ .Values.configNames.postgresPort }}: {{ .Values.postgresql.service.port | quote }}
  {{ .Values.configNames.postgresDbName }}: {{ .Values.postgresql.postgresqlDatabase }}
  {{ .Values.configNames.postgresUser }}: {{ .Values.postgresql.postgresqlUsername }}
  {{ .Values.configNames.rabbitmqHost }}: {{ include "rabbitmq.fullname" . }}
  {{ .Values.configNames.rabbitmqUser }}: {{ .Values.rabbitmq.auth.username }}
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
data:
  {{ .Values.configNames.postgresPassword }}: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{ .Values.configNames.rabbitmqPassword }}: {{ .Values.rabbitmq.auth.password | b64enc | quote }}