apiVersion: batch/v1
kind: Job
metadata:
  name: "stresstest-job"
  labels:
    helm.sh/chart: arch-chart-0.0.2
    app.kubernetes.io/name: arch-chart
    app.kubernetes.io/instance: archapp
    app.kubernetes.io/version: "0.0.7"
    app.kubernetes.io/managed-by: Helm
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: arch-chart
      labels:
        app.kubernetes.io/name: arch-chart
        app.kubernetes.io/instance: archapp
        helm.sh/chart: "arch-chart-0.0.2"
    spec:
      restartPolicy: Never
      containers:
        - name: stresstest-job
          image: jordi/ab@sha256:e73ba5f38be047448267bcfbab191bbea88017150578ef2dd3b0942a0e0d6a56
          command:
            - sh
            - "-c"
            - |
              while true; do ab -n50 -c5 -H "Host: arch.homework" http://nginx-nginx-ingress-controller/otusapp/api/v1/users/2c801978-815c-11ea-a3d4-02420a200002 ; sleep 3; done

  backoffLimit: 0
