replicaCount: 1

image:
  repository: ilyashikhaleev/arch-course-user

service:
  type: NodePort
  port: 9000

test:
  user: 2c801978-815c-11ea-a3d4-02420a200002

appPort: 8000

ingress:
  enabled: true
  hosts: ["arch.homework"]
  authenticated:
    paths: ["/api/v1/users"]
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: http,https
      #traefik.frontend.rule.type: PathPrefixStrip
      ingress.kubernetes.io/auth-type: forward
      ingress.kubernetes.io/auth-url: http://user-user-chart.arch-course.svc.cluster.local:9000/auth
      ingress.kubernetes.io/auth-response-headers: X-User-Id, X-Email, X-Login, X-First-Name, X-Last-Name
  guest:
    paths: ["/login", "/logout", "/api/v1/users/signup"]
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: http,https

postgresql:
  postgresqlDatabase: arch-course-db
  postgresqlUsername: arch-course
  postgresqlPassword: passwd
  service:
    port: "5432"

metrics:
  serviceMonitor:
    enabled: true

configNames:
  port: PORT
  postgresHost: POSTGRES_HOST
  postgresPort: POSTGRES_PORT
  postgresDbName: POSTGRES_DB
  postgresUser: POSTGRES_USER
  postgresPassword: POSTGRES_PASSWORD

prometheus-postgres-exporter:
  serviceMonitor:
    enabled: true
    interval: 15s
  config:
    autoDiscoverDatabases: true
    datasourceSecret:
      name: user-secret
      key: posgressUri

traefik:
  rbac:
    enabled: true
  accessLogs:
    enabled: true
  metrics:
    prometheus:
      enabled: true
    serviceMonitor:
      enabled: true
  ssl:
    enabled: false
  deployment:
    hostPort:
      httpEnabled: true
      httpPort: 8080
      httpsEnabled: false
  serviceType: NodePort
  debug:
    enabled: true

prometheus-operator:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelector: {}
  grafana:
    sidecar:
      dashboards:
        enabled: true
        label: grafana-dashboard
