apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  {{ .Values.configNames.port }}: {{ .Values.appPort | quote }}
  {{ .Values.configNames.postgresHost }}: {{ include "postgresql.fullname" . }}
  {{ .Values.configNames.postgresPort }}: {{ .Values.postgresql.service.port | quote }}
  {{ .Values.configNames.postgresDbName }}: {{ .Values.postgresql.postgresqlDatabase }}
  {{ .Values.configNames.postgresUser }}: {{ .Values.postgresql.postgresqlUsername }}
---
apiVersion: v1
kind: Secret
metadata:
  name: product-secret
type: Opaque
data:
  {{ .Values.configNames.postgresPassword }}: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}